name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: action/setup-node@v5
        with: 
          node-version: 20.0
      - run: npm install
      - run: npm run bulld
